/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as nftMarketplaceSol from './NFTMarketplace.sol/index.js';
export type { nftMarketplaceSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { NFTMarketplace } from './NFTMarketplace.sol/NFTMarketplace.js';
export { NFTMarketplace__factory } from './factories/NFTMarketplace.sol/NFTMarketplace__factory.js';