/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterSol from './Counter.sol/index.js';
export * as nftMarketplaceSol from './NFTMarketplace.sol/index.js';